/**
 * Clypra Text Effect Definition Output
 * Auto-generated by Clypra Text Effect Studio on 2026-05-26
 * Satisfies TextEffectDefinition interface structure
 */

export interface TextEffectDefinition {
  id: string;
  name: string;
  text: string;
  category: string;
  description: string;
  tags: string[];
  font: {
    family: string;
    weight: number;
    style: "normal" | "italic";
    letterSpacing: number;
    lineHeight: number;
  };
  fills: any[];
  strokes: any[];
  shadows: any[];
  glows?: any[];
  bevel?: any;
  panel?: any;
}

export interface BaseEffectConfig {
  glowLayers?: Array<{
    enabled: boolean;
    color: string;
    blur: number;
    opacity: number;
    type: "outer" | "inner";
    strength?: number;
    spread?: number;
  }>;
}
